/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "rtl/alu_4bit.v:3" *)
module alu_4bit(a, b, op, result, zero, negative, carry);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  (* src = "rtl/alu_4bit.v:4" *)
  input [3:0] a;
  (* src = "rtl/alu_4bit.v:5" *)
  input [3:0] b;
  (* src = "rtl/alu_4bit.v:10" *)
  output carry;
  (* src = "rtl/alu_4bit.v:9" *)
  output negative;
  (* src = "rtl/alu_4bit.v:6" *)
  input [2:0] op;
  (* src = "rtl/alu_4bit.v:7" *)
  output [3:0] result;
  (* src = "rtl/alu_4bit.v:8" *)
  output zero;
  assign _028_ = op[0] | ~(op[1]);
  assign _029_ = _028_ | ~(op[2]);
  assign _030_ = ~op[2];
  assign _031_ = op[1] | ~(op[0]);
  assign _032_ = ~(_031_ | _030_);
  assign _033_ = _032_ | ~(_029_);
  assign _034_ = op[1] | op[0];
  assign _035_ = _034_ | ~(op[2]);
  assign _036_ = ~(op[1] & op[0]);
  assign _037_ = _036_ | ~(_030_);
  assign _038_ = ~(_037_ & _035_);
  assign _039_ = ~(_038_ | _033_);
  assign _040_ = ~((op[1] & op[0]) | op[2]);
  assign _041_ = _040_ | ~(_039_);
  assign _042_ = ~_032_;
  assign _043_ = ~((_042_ & _029_) | a[0]);
  assign _044_ = ~(a[0] ^ b[0]);
  assign _045_ = ~(a[0] | b[0]);
  assign _046_ = ~((_044_ | _035_) & (_037_ | _045_));
  assign _047_ = _046_ | _043_;
  assign _048_ = _034_ | ~(_030_);
  assign _049_ = ~(_028_ | op[2]);
  assign _050_ = ~(_031_ | op[2]);
  assign _051_ = ~(a[0] & b[0]);
  assign _052_ = ~_051_;
  assign _053_ = _051_ & ~(_045_);
  assign _054_ = ~((_052_ & _049_) | (_050_ & _053_));
  assign _055_ = ~((_044_ | _048_) & _054_);
  assign _056_ = _055_ | _047_;
  assign result[0] = _041_ ? _056_ : b[0];
  assign _057_ = a[0] ^ a[1];
  assign _058_ = ~(a[0] ^ a[1]);
  assign _059_ = ~((_057_ | _029_) & (_042_ | _058_));
  assign _060_ = ~(a[1] ^ b[1]);
  assign _061_ = ~(a[1] | b[1]);
  assign _062_ = ~((_060_ | _035_) & (_037_ | _061_));
  assign _063_ = ~(_062_ | _059_);
  assign _064_ = a[1] & b[1];
  assign _065_ = a[1] ^ b[1];
  assign _066_ = b[0] & ~(a[0]);
  assign _067_ = _066_ ^ _065_;
  assign _068_ = ~((_064_ & _049_) | (_050_ & _067_));
  assign _069_ = ~(_060_ ^ _051_);
  assign _070_ = ~((_069_ | _048_) & _068_);
  assign _071_ = _070_ | ~(_063_);
  assign result[1] = _041_ ? _071_ : b[1];
  assign _072_ = ~(a[0] | a[1]);
  assign _073_ = ~(_072_ ^ a[2]);
  assign _074_ = ~(a[0] & a[1]);
  assign _075_ = _074_ ^ a[2];
  assign _076_ = ~((_073_ | _029_) & (_042_ | _075_));
  assign _077_ = ~(a[2] ^ b[2]);
  assign _078_ = ~(a[2] | b[2]);
  assign _079_ = ~((_077_ | _035_) & (_037_ | _078_));
  assign _080_ = _079_ | _076_;
  assign _081_ = a[2] & b[2];
  assign _082_ = _081_ | _078_;
  assign _083_ = b[1] | ~(a[1]);
  assign _084_ = ~((_066_ | _065_) & _083_);
  assign _085_ = _084_ ^ _082_;
  assign _086_ = ~((_081_ & _049_) | (_050_ & _085_));
  assign _087_ = ~(_060_ | _051_);
  assign _088_ = ~(_087_ | _064_);
  assign _089_ = ~(_088_ ^ _077_);
  assign _090_ = ~((_089_ | _048_) & _086_);
  assign _091_ = _090_ | _080_;
  assign result[2] = _041_ ? _091_ : b[2];
  assign _092_ = _072_ & ~(a[2]);
  assign _093_ = ~(_092_ ^ a[3]);
  assign _094_ = a[2] & ~(_074_);
  assign _095_ = ~(_094_ ^ a[3]);
  assign _096_ = ~((_093_ | _029_) & (_042_ | _095_));
  assign _097_ = ~(a[3] ^ b[3]);
  assign _098_ = ~(a[3] | b[3]);
  assign _099_ = ~((_097_ | _035_) & (_037_ | _098_));
  assign _100_ = ~(_099_ | _096_);
  assign _101_ = a[3] & b[3];
  assign _102_ = _101_ | _098_;
  assign _103_ = a[2] & ~(b[2]);
  assign _104_ = ~((_084_ & _082_) | _103_);
  assign _105_ = ~(_104_ ^ _102_);
  assign _106_ = ~((_101_ & _049_) | (_050_ & _105_));
  assign _000_ = ~_077_;
  assign _001_ = _087_ | _064_;
  assign _002_ = ~((_001_ & _000_) | _081_);
  assign _003_ = ~(_002_ ^ _097_);
  assign _004_ = ~((_003_ | _048_) & _106_);
  assign _005_ = _004_ | ~(_100_);
  assign negative = _041_ ? _005_ : b[3];
  assign _006_ = result[1] | result[0];
  assign _007_ = negative | result[2];
  assign zero = ~(_007_ | _006_);
  assign _008_ = ~(a[3] | a[2]);
  assign _009_ = a[3] | a[2];
  assign _010_ = ~((_009_ | _072_) & _008_);
  assign _011_ = _010_ & ~(_029_);
  assign _012_ = ~(a[3] & a[2]);
  assign _013_ = ~(_012_ | _074_);
  assign _014_ = ~((_013_ & _032_) | _011_);
  assign _015_ = a[3] & ~(b[3]);
  assign _016_ = ~((_102_ & _103_) | _015_);
  assign _017_ = ~(_102_ & _082_);
  assign _018_ = _017_ | ~(_084_);
  assign _019_ = ~(_018_ & _016_);
  assign _020_ = _081_ & ~(_097_);
  assign _021_ = ~(_020_ | _101_);
  assign _022_ = _097_ | _077_;
  assign _023_ = ~((_022_ | _088_) & _021_);
  assign _024_ = _023_ & ~(_048_);
  assign _025_ = ~((_019_ & _050_) | _024_);
  assign _026_ = _048_ & ~(_050_);
  assign _027_ = _026_ & ~(_033_);
  assign carry = ~((_025_ & _014_) | _027_);
  assign result[3] = negative;
endmodule

(* src = "rtl/control_unit.v:3" *)
module control_unit(opcode, zero, negative, imm_mode, reg_write, mem_read, mem_write, mem_to_reg, alu_src, alu_op, pc_src, reg_sel, flag_write);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "rtl/control_unit.v:13" *)
  output [2:0] alu_op;
  (* src = "rtl/control_unit.v:12" *)
  output alu_src;
  (* src = "rtl/control_unit.v:16" *)
  output flag_write;
  (* src = "rtl/control_unit.v:7" *)
  input imm_mode;
  (* src = "rtl/control_unit.v:9" *)
  output mem_read;
  (* src = "rtl/control_unit.v:11" *)
  output mem_to_reg;
  (* src = "rtl/control_unit.v:10" *)
  output mem_write;
  (* src = "rtl/control_unit.v:6" *)
  input negative;
  (* src = "rtl/control_unit.v:4" *)
  input [3:0] opcode;
  (* src = "rtl/control_unit.v:14" *)
  output pc_src;
  (* src = "rtl/control_unit.v:15" *)
  output [1:0] reg_sel;
  (* src = "rtl/control_unit.v:8" *)
  output reg_write;
  (* src = "rtl/control_unit.v:5" *)
  input zero;
  assign _000_ = opcode[1] | opcode[0];
  assign _001_ = opcode[3] | opcode[2];
  assign _002_ = opcode[1] | ~(opcode[0]);
  assign _003_ = ~((_002_ & _000_) | _001_);
  assign _004_ = opcode[0] | ~(opcode[1]);
  assign _005_ = opcode[3] | ~(opcode[2]);
  assign _006_ = ~((_004_ | _001_) & (_000_ | _005_));
  assign _007_ = _006_ | _003_;
  assign _008_ = ~(opcode[1] & opcode[0]);
  assign _009_ = ~(opcode[3] & opcode[2]);
  assign _010_ = ~((_008_ & _004_) | _009_);
  assign _011_ = ~((_002_ & _000_) | _009_);
  assign _012_ = ~(_011_ | _010_);
  assign _013_ = _012_ & ~(_007_);
  assign _014_ = opcode[2] | ~(opcode[3]);
  assign _015_ = ~(_014_ | _008_);
  assign _016_ = _015_ | ~(_013_);
  assign _017_ = ~(_014_ | _004_);
  assign _018_ = ~(_017_ | _016_);
  assign _019_ = ~(_014_ | _002_);
  assign _020_ = ~(_014_ | _000_);
  assign _021_ = _020_ | _019_;
  assign _022_ = _021_ | ~(_018_);
  assign _023_ = ~(_005_ | _002_);
  assign _024_ = ~((_008_ & _004_) | _005_);
  assign _025_ = _024_ | _023_;
  assign _026_ = ~(_008_ | _005_);
  assign _027_ = _026_ | _023_;
  assign _028_ = ~(_027_ | _019_);
  assign alu_op[0] = ~((_025_ | _022_) & _028_);
  assign _029_ = ~(_024_ | _017_);
  assign alu_op[1] = ~((_025_ | _022_) & _029_);
  assign _030_ = ~(_021_ | _017_);
  assign alu_op[2] = ~((_025_ | _022_) & _030_);
  assign _031_ = ~((_002_ & _000_) | _005_);
  assign _032_ = _031_ | _024_;
  assign _033_ = _032_ | ~(_030_);
  assign _034_ = _009_ | _008_;
  assign _035_ = ~((_004_ | _001_) & _034_);
  assign _036_ = ~(_035_ | _003_);
  assign _037_ = _009_ | _004_;
  assign _038_ = _009_ | _002_;
  assign _039_ = _038_ & _037_;
  assign _040_ = _009_ | _000_;
  assign _041_ = _015_ | ~(_040_);
  assign _042_ = _041_ | ~(_039_);
  assign _043_ = _042_ | ~(_036_);
  assign _044_ = _043_ | _033_;
  assign flag_write = _044_ ? _033_ : imm_mode;
  assign _045_ = ~imm_mode;
  assign reg_sel[0] = _044_ ? _033_ : _045_;
  assign _046_ = ~(_008_ | _001_);
  assign _047_ = ~((_005_ & _001_) | _000_);
  assign _048_ = ~((_004_ & _002_) | _005_);
  assign _049_ = ~(_048_ | _047_);
  assign _050_ = ~(_026_ | _020_);
  assign _051_ = _019_ | _017_;
  assign _052_ = _051_ | ~(_050_);
  assign _053_ = _052_ | ~(_049_);
  assign _054_ = _015_ | ~(_012_);
  assign _055_ = ~(_054_ | _053_);
  assign alu_src = _046_ ? imm_mode : _055_;
  assign _056_ = ~((_001_ | opcode[0]) & (opcode[1] | _005_));
  assign _057_ = ~(_024_ | _021_);
  assign _058_ = _056_ | ~(_057_);
  assign _059_ = _017_ | ~(_034_);
  assign _060_ = _046_ | ~(_037_);
  assign _061_ = ~(_060_ | _059_);
  assign _062_ = _015_ | _011_;
  assign _063_ = _062_ | ~(_061_);
  assign mem_read = ~(_063_ | _058_);
  assign _064_ = ~opcode[1];
  assign _065_ = ~((_001_ | opcode[0]) & (_064_ | _009_));
  assign reg_write = ~(_065_ | _062_);
  assign _066_ = _031_ | _003_;
  assign _067_ = _066_ | ~(_057_);
  assign mem_write = ~(_067_ | _063_);
  assign _068_ = negative & ~(_038_);
  assign _069_ = _040_ ? _068_ : zero;
  assign pc_src = _069_ | _015_;
  assign mem_to_reg = mem_read;
  assign reg_sel[1] = 1'h0;
endmodule

(* top =  1  *)
(* src = "rtl/cpu_top.v:3" *)
module cpu_top(clk, rst_n, out_port, halt_out, debug_r0);
  (* src = "rtl/cpu_top.v:139" *)
  wire _00_;
  (* src = "rtl/cpu_top.v:172" *)
  wire [3:0] _01_;
  (* src = "rtl/cpu_top.v:139" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "rtl/cpu_top.v:118" *)
  wire [3:0] alu_b;
  (* src = "rtl/cpu_top.v:24" *)
  wire [2:0] alu_op;
  (* src = "rtl/cpu_top.v:34" *)
  wire [3:0] alu_result;
  (* src = "rtl/cpu_top.v:23" *)
  wire alu_src;
  (* src = "rtl/cpu_top.v:36" *)
  (* unused_bits = "0" *)
  wire carry;
  (* src = "rtl/cpu_top.v:4" *)
  input clk;
  (* src = "rtl/cpu_top.v:8" *)
  output [3:0] debug_r0;
  (* src = "rtl/cpu_top.v:26" *)
  wire flag_write;
  (* src = "rtl/cpu_top.v:14" *)
  wire halt;
  (* src = "rtl/cpu_top.v:7" *)
  output halt_out;
  (* src = "rtl/cpu_top.v:19" *)
  wire imm_mode;
  (* src = "rtl/cpu_top.v:20" *)
  wire [3:0] imm_val;
  (* src = "rtl/cpu_top.v:50" *)
  wire [8:0] instruction;
  (* src = "rtl/cpu_top.v:23" *)
  wire mem_read;
  (* src = "rtl/cpu_top.v:43" *)
  wire [3:0] mem_read_data;
  (* src = "rtl/cpu_top.v:23" *)
  wire mem_to_reg;
  (* src = "rtl/cpu_top.v:23" *)
  wire mem_write;
  (* src = "rtl/cpu_top.v:36" *)
  wire negative;
  (* src = "rtl/cpu_top.v:40" *)
  reg negative_r;
  (* src = "rtl/cpu_top.v:17" *)
  wire [3:0] opcode;
  (* src = "rtl/cpu_top.v:18" *)
  wire [3:0] operand;
  (* src = "rtl/cpu_top.v:6" *)
  output [3:0] out_port;
  (* src = "rtl/cpu_top.v:46" *)
  reg [3:0] out_reg;
  (* src = "rtl/cpu_top.v:12" *)
  wire [3:0] pc;
  (* src = "rtl/cpu_top.v:12" *)
  wire [3:0] pc_next;
  (* src = "rtl/cpu_top.v:23" *)
  wire pc_src;
  (* src = "rtl/cpu_top.v:13" *)
  wire pc_write;
  (* src = "rtl/cpu_top.v:29" *)
  wire [3:0] read_data1;
  (* src = "rtl/cpu_top.v:29" *)
  wire [3:0] read_data2;
  (* src = "rtl/cpu_top.v:99" *)
  wire [1:0] read_reg1_mux;
  (* src = "rtl/cpu_top.v:25" *)
  wire [1:0] reg_sel;
  (* src = "rtl/cpu_top.v:23" *)
  wire reg_write;
  (* src = "rtl/cpu_top.v:185" *)
  wire \rf.r0 ;
  (* src = "rtl/cpu_top.v:5" *)
  input rst_n;
  (* src = "rtl/cpu_top.v:30" *)
  wire [3:0] write_data;
  (* src = "rtl/cpu_top.v:31" *)
  wire [1:0] write_reg;
  (* src = "rtl/cpu_top.v:36" *)
  wire zero;
  (* src = "rtl/cpu_top.v:40" *)
  reg zero_r;
  assign _04_ = ~(instruction[5] & instruction[4]);
  assign _05_ = ~(instruction[7] & instruction[6]);
  assign halt = ~(_05_ | _04_);
  assign pc_write = ~halt;
  assign _06_ = reg_sel[1] | ~(reg_sel[0]);
  assign write_reg[0] = instruction[2] & ~(_06_);
  assign write_reg[1] = instruction[3] & ~(_06_);
  assign _07_ = instruction[4] | ~(instruction[5]);
  assign _08_ = ~(_07_ | _05_);
  assign _09_ = _08_ ? instruction[0] : instruction[2];
  assign _10_ = instruction[7] | instruction[6];
  assign _11_ = ~(_10_ | _07_);
  assign read_reg1_mux[0] = _09_ & ~(_11_);
  assign _12_ = _08_ ? instruction[1] : instruction[3];
  assign read_reg1_mux[1] = _12_ & ~(_11_);
  assign alu_b[0] = alu_src ? instruction[0] : read_data2[0];
  assign alu_b[1] = alu_src ? instruction[1] : read_data2[1];
  assign alu_b[2] = alu_src ? instruction[2] : read_data2[2];
  assign alu_b[3] = alu_src ? instruction[3] : read_data2[3];
  assign write_data[0] = mem_to_reg ? mem_read_data[0] : alu_result[0];
  assign write_data[1] = mem_to_reg ? mem_read_data[1] : alu_result[1];
  assign write_data[2] = mem_to_reg ? mem_read_data[2] : alu_result[2];
  assign write_data[3] = mem_to_reg ? mem_read_data[3] : alu_result[3];
  assign _13_ = ~pc[0];
  assign pc_next[0] = pc_src ? instruction[0] : _13_;
  assign _14_ = pc[0] ^ pc[1];
  assign pc_next[1] = pc_src ? instruction[1] : _14_;
  assign _15_ = ~(pc[0] & pc[1]);
  assign _16_ = ~(_15_ ^ pc[2]);
  assign pc_next[2] = pc_src ? instruction[2] : _16_;
  assign _17_ = _15_ | ~(pc[2]);
  assign _18_ = ~(_17_ ^ pc[3]);
  assign pc_next[3] = pc_src ? instruction[3] : _18_;
  assign _00_ = flag_write ? negative : negative_r;
  assign _03_ = _07_ | _05_;
  assign _01_[0] = _03_ ? out_reg[0] : read_data1[0];
  assign _01_[1] = _03_ ? out_reg[1] : read_data1[1];
  assign _01_[2] = _03_ ? out_reg[2] : read_data1[2];
  assign _01_[3] = _03_ ? out_reg[3] : read_data1[3];
  assign _02_ = flag_write ? zero : zero_r;
  (* src = "rtl/cpu_top.v:172" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      out_reg[0] <= 0;
    else
      out_reg[0] <= _01_[0];
  (* src = "rtl/cpu_top.v:172" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      out_reg[1] <= 0;
    else
      out_reg[1] <= _01_[1];
  (* src = "rtl/cpu_top.v:172" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      out_reg[2] <= 0;
    else
      out_reg[2] <= _01_[2];
  (* src = "rtl/cpu_top.v:172" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      out_reg[3] <= 0;
    else
      out_reg[3] <= _01_[3];
  (* src = "rtl/cpu_top.v:139" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      zero_r <= 0;
    else
      zero_r <= _02_;
  (* src = "rtl/cpu_top.v:139" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      negative_r <= 0;
    else
      negative_r <= _00_;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:125" *)
  alu_4bit alu (
    .a(read_data1),
    .b(alu_b),
    .carry(carry),
    .negative(negative),
    .op(alu_op),
    .result(alu_result),
    .zero(zero)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:80" *)
  control_unit ctrl (
    .alu_op(alu_op),
    .alu_src(alu_src),
    .flag_write(flag_write),
    .imm_mode(instruction[8]),
    .mem_read(mem_read),
    .mem_to_reg(mem_to_reg),
    .mem_write(mem_write),
    .negative(negative_r),
    .opcode(instruction[7:4]),
    .pc_src(pc_src),
    .reg_sel(reg_sel),
    .reg_write(reg_write),
    .zero(zero_r)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:150" *)
  data_memory dmem (
    .addr(instruction[3:0]),
    .clk(clk),
    .mem_read(mem_read),
    .mem_write(mem_write),
    .read_data(mem_read_data),
    .write_data(read_data1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:62" *)
  instruction_memory imem (
    .addr(pc),
    .instruction(instruction)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:53" *)
  program_counter pc_inst (
    .clk(clk),
    .halt(halt),
    .pc(pc),
    .pc_next(pc_next),
    .pc_write(pc_write),
    .rst_n(rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:105" *)
  register_file rf (
    .clk(clk),
    .read_data1(read_data1),
    .read_data2(read_data2),
    .read_reg1(read_reg1_mux),
    .read_reg2(instruction[1:0]),
    .reg_write(reg_write),
    .rst_n(rst_n),
    .write_data(write_data),
    .write_reg(write_reg)
  );
  assign debug_r0 = 4'b000x;
  assign halt_out = halt;
  assign imm_mode = instruction[8];
  assign imm_val = instruction[3:0];
  assign opcode = instruction[7:4];
  assign operand = instruction[3:0];
  assign out_port = out_reg;
  assign \rf.r0  = 1'hx;
endmodule

(* src = "rtl/data_memory.v:3" *)
module data_memory(clk, mem_read, mem_write, addr, write_data, read_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  (* src = "rtl/data_memory.v:7" *)
  input [3:0] addr;
  (* src = "rtl/data_memory.v:4" *)
  input clk;
  (* src = "rtl/data_memory.v:15" *)
  wire [31:0] i;
  (* src = "rtl/data_memory.v:5" *)
  input mem_read;
  (* src = "rtl/data_memory.v:6" *)
  input mem_write;
  (* init = 4'h0 *)
  reg [3:0] \ram[0]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[10]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[11]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[12]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[13]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[14]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[15]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[1]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[2]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[3]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[4]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[5]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[6]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[7]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[8]  = 4'h0;
  (* init = 4'h0 *)
  reg [3:0] \ram[9]  = 4'h0;
  (* src = "rtl/data_memory.v:9" *)
  output [3:0] read_data;
  (* src = "rtl/data_memory.v:8" *)
  input [3:0] write_data;
  assign _064_ = addr[1] & ~(addr[0]);
  assign _065_ = addr[3] & ~(addr[2]);
  assign _066_ = ~(_065_ & _064_);
  assign _067_ = mem_write & ~(_066_);
  assign _004_ = _067_ ? write_data[0] : \ram[10] [0];
  assign _005_ = _067_ ? write_data[1] : \ram[10] [1];
  assign _006_ = _067_ ? write_data[2] : \ram[10] [2];
  assign _007_ = _067_ ? write_data[3] : \ram[10] [3];
  assign _068_ = ~mem_read;
  assign _069_ = addr[0] ? \ram[1] [0] : \ram[0] [0];
  assign _070_ = addr[0] ? \ram[3] [0] : \ram[2] [0];
  assign _071_ = addr[1] ? _070_ : _069_;
  assign _072_ = addr[0] ? \ram[5] [0] : \ram[4] [0];
  assign _073_ = addr[0] ? \ram[7] [0] : \ram[6] [0];
  assign _074_ = addr[1] ? _073_ : _072_;
  assign _075_ = addr[2] ? _074_ : _071_;
  assign _076_ = addr[0] ? \ram[9] [0] : \ram[8] [0];
  assign _077_ = addr[0] ? \ram[11] [0] : \ram[10] [0];
  assign _078_ = addr[1] ? _077_ : _076_;
  assign _079_ = addr[0] ? \ram[13] [0] : \ram[12] [0];
  assign _080_ = addr[0] ? \ram[15] [0] : \ram[14] [0];
  assign _081_ = addr[1] ? _080_ : _079_;
  assign _082_ = addr[2] ? _081_ : _078_;
  assign _083_ = addr[3] ? _082_ : _075_;
  assign read_data[0] = _083_ & ~(_068_);
  assign _084_ = addr[0] ? \ram[1] [1] : \ram[0] [1];
  assign _085_ = addr[0] ? \ram[3] [1] : \ram[2] [1];
  assign _086_ = addr[1] ? _085_ : _084_;
  assign _087_ = addr[0] ? \ram[5] [1] : \ram[4] [1];
  assign _088_ = addr[0] ? \ram[7] [1] : \ram[6] [1];
  assign _089_ = addr[1] ? _088_ : _087_;
  assign _090_ = addr[2] ? _089_ : _086_;
  assign _091_ = addr[0] ? \ram[9] [1] : \ram[8] [1];
  assign _092_ = addr[0] ? \ram[11] [1] : \ram[10] [1];
  assign _093_ = addr[1] ? _092_ : _091_;
  assign _094_ = addr[0] ? \ram[13] [1] : \ram[12] [1];
  assign _095_ = addr[0] ? \ram[15] [1] : \ram[14] [1];
  assign _096_ = addr[1] ? _095_ : _094_;
  assign _097_ = addr[2] ? _096_ : _093_;
  assign _098_ = addr[3] ? _097_ : _090_;
  assign read_data[1] = _098_ & ~(_068_);
  assign _099_ = addr[0] ? \ram[1] [2] : \ram[0] [2];
  assign _100_ = addr[0] ? \ram[3] [2] : \ram[2] [2];
  assign _101_ = addr[1] ? _100_ : _099_;
  assign _102_ = addr[0] ? \ram[5] [2] : \ram[4] [2];
  assign _103_ = addr[0] ? \ram[7] [2] : \ram[6] [2];
  assign _104_ = addr[1] ? _103_ : _102_;
  assign _105_ = addr[2] ? _104_ : _101_;
  assign _106_ = addr[0] ? \ram[9] [2] : \ram[8] [2];
  assign _107_ = addr[0] ? \ram[11] [2] : \ram[10] [2];
  assign _108_ = addr[1] ? _107_ : _106_;
  assign _109_ = addr[0] ? \ram[13] [2] : \ram[12] [2];
  assign _110_ = addr[0] ? \ram[15] [2] : \ram[14] [2];
  assign _111_ = addr[1] ? _110_ : _109_;
  assign _112_ = addr[2] ? _111_ : _108_;
  assign _113_ = addr[3] ? _112_ : _105_;
  assign read_data[2] = _113_ & ~(_068_);
  assign _114_ = addr[0] ? \ram[1] [3] : \ram[0] [3];
  assign _115_ = addr[0] ? \ram[3] [3] : \ram[2] [3];
  assign _116_ = addr[1] ? _115_ : _114_;
  assign _117_ = addr[0] ? \ram[5] [3] : \ram[4] [3];
  assign _118_ = addr[0] ? \ram[7] [3] : \ram[6] [3];
  assign _119_ = addr[1] ? _118_ : _117_;
  assign _120_ = addr[2] ? _119_ : _116_;
  assign _121_ = addr[0] ? \ram[9] [3] : \ram[8] [3];
  assign _122_ = addr[0] ? \ram[11] [3] : \ram[10] [3];
  assign _123_ = addr[1] ? _122_ : _121_;
  assign _124_ = addr[0] ? \ram[13] [3] : \ram[12] [3];
  assign _125_ = addr[0] ? \ram[15] [3] : \ram[14] [3];
  assign _126_ = addr[1] ? _125_ : _124_;
  assign _127_ = addr[2] ? _126_ : _123_;
  assign _128_ = addr[3] ? _127_ : _120_;
  assign read_data[3] = _128_ & ~(_068_);
  assign _129_ = ~(addr[1] | addr[0]);
  assign _130_ = addr[3] | addr[2];
  assign _131_ = _130_ | ~(_129_);
  assign _132_ = _131_ | ~(mem_write);
  assign _000_ = _132_ ? \ram[0] [0] : write_data[0];
  assign _001_ = _132_ ? \ram[0] [1] : write_data[1];
  assign _002_ = _132_ ? \ram[0] [2] : write_data[2];
  assign _003_ = _132_ ? \ram[0] [3] : write_data[3];
  assign _133_ = ~(addr[3] | addr[2]);
  assign _134_ = addr[1] | ~(addr[0]);
  assign _135_ = _134_ | ~(_133_);
  assign _136_ = _135_ | ~(mem_write);
  assign _028_ = _136_ ? \ram[1] [0] : write_data[0];
  assign _029_ = _136_ ? \ram[1] [1] : write_data[1];
  assign _030_ = _136_ ? \ram[1] [2] : write_data[2];
  assign _031_ = _136_ ? \ram[1] [3] : write_data[3];
  assign _137_ = _130_ | ~(_064_);
  assign _138_ = _137_ | ~(mem_write);
  assign _032_ = _138_ ? \ram[2] [0] : write_data[0];
  assign _033_ = _138_ ? \ram[2] [1] : write_data[1];
  assign _034_ = _138_ ? \ram[2] [2] : write_data[2];
  assign _035_ = _138_ ? \ram[2] [3] : write_data[3];
  assign _139_ = addr[1] & addr[0];
  assign _140_ = ~(addr[3] & addr[2]);
  assign _141_ = _140_ | ~(_139_);
  assign _142_ = _141_ | ~(mem_write);
  assign _024_ = _142_ ? \ram[15] [0] : write_data[0];
  assign _025_ = _142_ ? \ram[15] [1] : write_data[1];
  assign _026_ = _142_ ? \ram[15] [2] : write_data[2];
  assign _027_ = _142_ ? \ram[15] [3] : write_data[3];
  assign _143_ = ~(addr[1] & addr[0]);
  assign _144_ = _143_ | ~(_133_);
  assign _145_ = _144_ | ~(mem_write);
  assign _036_ = _145_ ? \ram[3] [0] : write_data[0];
  assign _037_ = _145_ ? \ram[3] [1] : write_data[1];
  assign _038_ = _145_ ? \ram[3] [2] : write_data[2];
  assign _039_ = _145_ ? \ram[3] [3] : write_data[3];
  assign _146_ = _140_ | ~(_064_);
  assign _147_ = _146_ | ~(mem_write);
  assign _020_ = _147_ ? \ram[14] [0] : write_data[0];
  assign _021_ = _147_ ? \ram[14] [1] : write_data[1];
  assign _022_ = _147_ ? \ram[14] [2] : write_data[2];
  assign _023_ = _147_ ? \ram[14] [3] : write_data[3];
  assign _148_ = addr[0] & ~(addr[1]);
  assign _149_ = _140_ | ~(_148_);
  assign _150_ = _149_ | ~(mem_write);
  assign _016_ = _150_ ? \ram[13] [0] : write_data[0];
  assign _017_ = _150_ ? \ram[13] [1] : write_data[1];
  assign _018_ = _150_ ? \ram[13] [2] : write_data[2];
  assign _019_ = _150_ ? \ram[13] [3] : write_data[3];
  assign _151_ = addr[3] | ~(addr[2]);
  assign _152_ = _151_ | ~(_129_);
  assign _153_ = _152_ | ~(mem_write);
  assign _040_ = _153_ ? \ram[4] [0] : write_data[0];
  assign _041_ = _153_ ? \ram[4] [1] : write_data[1];
  assign _042_ = _153_ ? \ram[4] [2] : write_data[2];
  assign _043_ = _153_ ? \ram[4] [3] : write_data[3];
  assign _154_ = _140_ | ~(_129_);
  assign _155_ = _154_ | ~(mem_write);
  assign _012_ = _155_ ? \ram[12] [0] : write_data[0];
  assign _013_ = _155_ ? \ram[12] [1] : write_data[1];
  assign _014_ = _155_ ? \ram[12] [2] : write_data[2];
  assign _015_ = _155_ ? \ram[12] [3] : write_data[3];
  assign _156_ = _151_ | ~(_148_);
  assign _157_ = _156_ | ~(mem_write);
  assign _044_ = _157_ ? \ram[5] [0] : write_data[0];
  assign _045_ = _157_ ? \ram[5] [1] : write_data[1];
  assign _046_ = _157_ ? \ram[5] [2] : write_data[2];
  assign _047_ = _157_ ? \ram[5] [3] : write_data[3];
  assign _158_ = _151_ | ~(_064_);
  assign _159_ = _158_ | ~(mem_write);
  assign _048_ = _159_ ? \ram[6] [0] : write_data[0];
  assign _049_ = _159_ ? \ram[6] [1] : write_data[1];
  assign _050_ = _159_ ? \ram[6] [2] : write_data[2];
  assign _051_ = _159_ ? \ram[6] [3] : write_data[3];
  assign _160_ = _143_ | ~(_065_);
  assign _161_ = _160_ | ~(mem_write);
  assign _008_ = _161_ ? \ram[11] [0] : write_data[0];
  assign _009_ = _161_ ? \ram[11] [1] : write_data[1];
  assign _010_ = _161_ ? \ram[11] [2] : write_data[2];
  assign _011_ = _161_ ? \ram[11] [3] : write_data[3];
  assign _162_ = _151_ | ~(_139_);
  assign _163_ = _162_ | ~(mem_write);
  assign _052_ = _163_ ? \ram[7] [0] : write_data[0];
  assign _053_ = _163_ ? \ram[7] [1] : write_data[1];
  assign _054_ = _163_ ? \ram[7] [2] : write_data[2];
  assign _055_ = _163_ ? \ram[7] [3] : write_data[3];
  assign _164_ = ~(_129_ & _065_);
  assign _165_ = _164_ | ~(mem_write);
  assign _056_ = _165_ ? \ram[8] [0] : write_data[0];
  assign _057_ = _165_ ? \ram[8] [1] : write_data[1];
  assign _058_ = _165_ ? \ram[8] [2] : write_data[2];
  assign _059_ = _165_ ? \ram[8] [3] : write_data[3];
  assign _166_ = _134_ | ~(_065_);
  assign _167_ = _166_ | ~(mem_write);
  assign _060_ = _167_ ? \ram[9] [0] : write_data[0];
  assign _061_ = _167_ ? \ram[9] [1] : write_data[1];
  assign _062_ = _167_ ? \ram[9] [2] : write_data[2];
  assign _063_ = _167_ ? \ram[9] [3] : write_data[3];
  always @(posedge clk)
      \ram[15] [0] <= _024_;
  always @(posedge clk)
      \ram[15] [1] <= _025_;
  always @(posedge clk)
      \ram[15] [2] <= _026_;
  always @(posedge clk)
      \ram[15] [3] <= _027_;
  always @(posedge clk)
      \ram[14] [0] <= _020_;
  always @(posedge clk)
      \ram[14] [1] <= _021_;
  always @(posedge clk)
      \ram[14] [2] <= _022_;
  always @(posedge clk)
      \ram[14] [3] <= _023_;
  always @(posedge clk)
      \ram[13] [0] <= _016_;
  always @(posedge clk)
      \ram[13] [1] <= _017_;
  always @(posedge clk)
      \ram[13] [2] <= _018_;
  always @(posedge clk)
      \ram[13] [3] <= _019_;
  always @(posedge clk)
      \ram[12] [0] <= _012_;
  always @(posedge clk)
      \ram[12] [1] <= _013_;
  always @(posedge clk)
      \ram[12] [2] <= _014_;
  always @(posedge clk)
      \ram[12] [3] <= _015_;
  always @(posedge clk)
      \ram[11] [0] <= _008_;
  always @(posedge clk)
      \ram[11] [1] <= _009_;
  always @(posedge clk)
      \ram[11] [2] <= _010_;
  always @(posedge clk)
      \ram[11] [3] <= _011_;
  always @(posedge clk)
      \ram[10] [0] <= _004_;
  always @(posedge clk)
      \ram[10] [1] <= _005_;
  always @(posedge clk)
      \ram[10] [2] <= _006_;
  always @(posedge clk)
      \ram[10] [3] <= _007_;
  always @(posedge clk)
      \ram[2] [0] <= _032_;
  always @(posedge clk)
      \ram[2] [1] <= _033_;
  always @(posedge clk)
      \ram[2] [2] <= _034_;
  always @(posedge clk)
      \ram[2] [3] <= _035_;
  always @(posedge clk)
      \ram[9] [0] <= _060_;
  always @(posedge clk)
      \ram[9] [1] <= _061_;
  always @(posedge clk)
      \ram[9] [2] <= _062_;
  always @(posedge clk)
      \ram[9] [3] <= _063_;
  always @(posedge clk)
      \ram[8] [0] <= _056_;
  always @(posedge clk)
      \ram[8] [1] <= _057_;
  always @(posedge clk)
      \ram[8] [2] <= _058_;
  always @(posedge clk)
      \ram[8] [3] <= _059_;
  always @(posedge clk)
      \ram[7] [0] <= _052_;
  always @(posedge clk)
      \ram[7] [1] <= _053_;
  always @(posedge clk)
      \ram[7] [2] <= _054_;
  always @(posedge clk)
      \ram[7] [3] <= _055_;
  always @(posedge clk)
      \ram[6] [0] <= _048_;
  always @(posedge clk)
      \ram[6] [1] <= _049_;
  always @(posedge clk)
      \ram[6] [2] <= _050_;
  always @(posedge clk)
      \ram[6] [3] <= _051_;
  always @(posedge clk)
      \ram[5] [0] <= _044_;
  always @(posedge clk)
      \ram[5] [1] <= _045_;
  always @(posedge clk)
      \ram[5] [2] <= _046_;
  always @(posedge clk)
      \ram[5] [3] <= _047_;
  always @(posedge clk)
      \ram[0] [0] <= _000_;
  always @(posedge clk)
      \ram[0] [1] <= _001_;
  always @(posedge clk)
      \ram[0] [2] <= _002_;
  always @(posedge clk)
      \ram[0] [3] <= _003_;
  always @(posedge clk)
      \ram[1] [0] <= _028_;
  always @(posedge clk)
      \ram[1] [1] <= _029_;
  always @(posedge clk)
      \ram[1] [2] <= _030_;
  always @(posedge clk)
      \ram[1] [3] <= _031_;
  always @(posedge clk)
      \ram[3] [0] <= _036_;
  always @(posedge clk)
      \ram[3] [1] <= _037_;
  always @(posedge clk)
      \ram[3] [2] <= _038_;
  always @(posedge clk)
      \ram[3] [3] <= _039_;
  always @(posedge clk)
      \ram[4] [0] <= _040_;
  always @(posedge clk)
      \ram[4] [1] <= _041_;
  always @(posedge clk)
      \ram[4] [2] <= _042_;
  always @(posedge clk)
      \ram[4] [3] <= _043_;
  assign i = 32'd16;
endmodule

(* src = "rtl/instruction_memory.v:3" *)
module instruction_memory(addr, instruction);
  (* src = "rtl/instruction_memory.v:4" *)
  input [3:0] addr;
  (* src = "rtl/instruction_memory.v:10" *)
  wire [31:0] i;
  (* src = "rtl/instruction_memory.v:5" *)
  output [8:0] instruction;
  wire [8:0] \rom[0] ;
  wire [8:0] \rom[10] ;
  wire [8:0] \rom[11] ;
  wire [8:0] \rom[12] ;
  wire [8:0] \rom[13] ;
  wire [8:0] \rom[14] ;
  wire [8:0] \rom[15] ;
  wire [8:0] \rom[1] ;
  wire [8:0] \rom[2] ;
  wire [8:0] \rom[3] ;
  wire [8:0] \rom[4] ;
  wire [8:0] \rom[5] ;
  wire [8:0] \rom[6] ;
  wire [8:0] \rom[7] ;
  wire [8:0] \rom[8] ;
  wire [8:0] \rom[9] ;
  assign i = 32'd16;
  assign instruction = 9'h000;
  assign \rom[0]  = 9'h000;
  assign \rom[10]  = 9'h000;
  assign \rom[11]  = 9'h000;
  assign \rom[12]  = 9'h000;
  assign \rom[13]  = 9'h000;
  assign \rom[14]  = 9'h000;
  assign \rom[15]  = 9'h000;
  assign \rom[1]  = 9'h000;
  assign \rom[2]  = 9'h000;
  assign \rom[3]  = 9'h000;
  assign \rom[4]  = 9'h000;
  assign \rom[5]  = 9'h000;
  assign \rom[6]  = 9'h000;
  assign \rom[7]  = 9'h000;
  assign \rom[8]  = 9'h000;
  assign \rom[9]  = 9'h000;
endmodule

(* src = "rtl/program_counter.v:3" *)
module program_counter(clk, rst_n, pc_write, halt, pc_next, pc);
  (* src = "rtl/program_counter.v:13" *)
  wire [3:0] _00_;
  wire _01_;
  (* src = "rtl/program_counter.v:4" *)
  input clk;
  (* src = "rtl/program_counter.v:7" *)
  input halt;
  (* src = "rtl/program_counter.v:9" *)
  output [3:0] pc;
  reg [3:0] pc;
  (* src = "rtl/program_counter.v:8" *)
  input [3:0] pc_next;
  (* src = "rtl/program_counter.v:6" *)
  input pc_write;
  (* src = "rtl/program_counter.v:5" *)
  input rst_n;
  assign _01_ = pc_write & ~(halt);
  assign _00_[0] = _01_ ? pc_next[0] : pc[0];
  assign _00_[1] = _01_ ? pc_next[1] : pc[1];
  assign _00_[2] = _01_ ? pc_next[2] : pc[2];
  assign _00_[3] = _01_ ? pc_next[3] : pc[3];
  (* src = "rtl/program_counter.v:13" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      pc[0] <= 0;
    else
      pc[0] <= _00_[0];
  (* src = "rtl/program_counter.v:13" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      pc[1] <= 0;
    else
      pc[1] <= _00_[1];
  (* src = "rtl/program_counter.v:13" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      pc[2] <= 0;
    else
      pc[2] <= _00_[2];
  (* src = "rtl/program_counter.v:13" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      pc[3] <= 0;
    else
      pc[3] <= _00_[3];
endmodule

(* src = "rtl/register_file.v:3" *)
module register_file(clk, rst_n, reg_write, read_reg1, read_reg2, write_reg, write_data, read_data1, read_data2);
  (* src = "rtl/register_file.v:18" *)
  wire [3:0] _000_;
  (* src = "rtl/register_file.v:18" *)
  wire [3:0] _001_;
  (* src = "rtl/register_file.v:18" *)
  wire [3:0] _002_;
  (* src = "rtl/register_file.v:18" *)
  wire [3:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  (* src = "rtl/register_file.v:4" *)
  input clk;
  (* src = "rtl/register_file.v:15" *)
  reg [3:0] r0;
  (* src = "rtl/register_file.v:15" *)
  reg [3:0] r1;
  (* src = "rtl/register_file.v:15" *)
  reg [3:0] r2;
  (* src = "rtl/register_file.v:15" *)
  reg [3:0] r3;
  (* src = "rtl/register_file.v:11" *)
  output [3:0] read_data1;
  (* src = "rtl/register_file.v:12" *)
  output [3:0] read_data2;
  (* src = "rtl/register_file.v:7" *)
  input [1:0] read_reg1;
  (* src = "rtl/register_file.v:8" *)
  input [1:0] read_reg2;
  (* src = "rtl/register_file.v:6" *)
  input reg_write;
  (* src = "rtl/register_file.v:5" *)
  input rst_n;
  (* src = "rtl/register_file.v:10" *)
  input [3:0] write_data;
  (* src = "rtl/register_file.v:9" *)
  input [1:0] write_reg;
  assign _022_ = write_reg[0] | ~(write_reg[1]);
  assign _023_ = _022_ ? r2[0] : write_data[0];
  assign _002_[0] = reg_write ? _023_ : r2[0];
  assign _024_ = _022_ ? r2[1] : write_data[1];
  assign _002_[1] = reg_write ? _024_ : r2[1];
  assign _025_ = _022_ ? r2[2] : write_data[2];
  assign _002_[2] = reg_write ? _025_ : r2[2];
  assign _026_ = _022_ ? r2[3] : write_data[3];
  assign _002_[3] = reg_write ? _026_ : r2[3];
  assign _027_ = write_reg[1] | ~(write_reg[0]);
  assign _028_ = _027_ ? r1[0] : write_data[0];
  assign _001_[0] = reg_write ? _028_ : r1[0];
  assign _029_ = _027_ ? r1[1] : write_data[1];
  assign _001_[1] = reg_write ? _029_ : r1[1];
  assign _030_ = _027_ ? r1[2] : write_data[2];
  assign _001_[2] = reg_write ? _030_ : r1[2];
  assign _031_ = _027_ ? r1[3] : write_data[3];
  assign _001_[3] = reg_write ? _031_ : r1[3];
  assign _032_ = write_reg[0] | write_reg[1];
  assign _033_ = _032_ ? r0[0] : write_data[0];
  assign _000_[0] = reg_write ? _033_ : r0[0];
  assign _034_ = _032_ ? r0[1] : write_data[1];
  assign _000_[1] = reg_write ? _034_ : r0[1];
  assign _035_ = _032_ ? r0[2] : write_data[2];
  assign _000_[2] = reg_write ? _035_ : r0[2];
  assign _036_ = _032_ ? r0[3] : write_data[3];
  assign _000_[3] = reg_write ? _036_ : r0[3];
  assign _037_ = ~(write_reg[0] & write_reg[1]);
  assign _038_ = _037_ ? r3[0] : write_data[0];
  assign _003_[0] = reg_write ? _038_ : r3[0];
  assign _039_ = _037_ ? r3[1] : write_data[1];
  assign _003_[1] = reg_write ? _039_ : r3[1];
  assign _040_ = _037_ ? r3[2] : write_data[2];
  assign _003_[2] = reg_write ? _040_ : r3[2];
  assign _041_ = _037_ ? r3[3] : write_data[3];
  assign _003_[3] = reg_write ? _041_ : r3[3];
  assign _042_ = read_reg2[0] | read_reg2[1];
  assign _043_ = ~r1[0];
  assign _044_ = read_reg2[1] | ~(read_reg2[0]);
  assign _045_ = read_reg2[0] & read_reg2[1];
  assign _046_ = read_reg2[1] & ~(read_reg2[0]);
  assign _047_ = ~((_045_ & r3[0]) | (r2[0] & _046_));
  assign _048_ = ~((_044_ | _043_) & _047_);
  assign read_data2[0] = _042_ ? _048_ : r0[0];
  assign _049_ = ~r1[1];
  assign _050_ = ~((_045_ & r3[1]) | (r2[1] & _046_));
  assign _051_ = ~((_044_ | _049_) & _050_);
  assign read_data2[1] = _042_ ? _051_ : r0[1];
  assign _004_ = ~r1[2];
  assign _005_ = ~((_045_ & r3[2]) | (r2[2] & _046_));
  assign _006_ = ~((_044_ | _004_) & _005_);
  assign read_data2[2] = _042_ ? _006_ : r0[2];
  assign _007_ = ~r1[3];
  assign _008_ = ~((_045_ & r3[3]) | (r2[3] & _046_));
  assign _009_ = ~((_044_ | _007_) & _008_);
  assign read_data2[3] = _042_ ? _009_ : r0[3];
  assign _010_ = read_reg1[1] | read_reg1[0];
  assign _011_ = read_reg1[1] | ~(read_reg1[0]);
  assign _012_ = read_reg1[1] & read_reg1[0];
  assign _013_ = read_reg1[1] & ~(read_reg1[0]);
  assign _014_ = ~((_012_ & r3[0]) | (r2[0] & _013_));
  assign _015_ = ~((_011_ | _043_) & _014_);
  assign read_data1[0] = _010_ ? _015_ : r0[0];
  assign _016_ = ~((_012_ & r3[1]) | (r2[1] & _013_));
  assign _017_ = ~((_011_ | _049_) & _016_);
  assign read_data1[1] = _010_ ? _017_ : r0[1];
  assign _018_ = ~((_012_ & r3[2]) | (r2[2] & _013_));
  assign _019_ = ~((_011_ | _004_) & _018_);
  assign read_data1[2] = _010_ ? _019_ : r0[2];
  assign _020_ = ~((_012_ & r3[3]) | (r2[3] & _013_));
  assign _021_ = ~((_011_ | _007_) & _020_);
  assign read_data1[3] = _010_ ? _021_ : r0[3];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r3[0] <= 0;
    else
      r3[0] <= _003_[0];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r3[1] <= 0;
    else
      r3[1] <= _003_[1];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r3[2] <= 0;
    else
      r3[2] <= _003_[2];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r3[3] <= 0;
    else
      r3[3] <= _003_[3];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r0[0] <= 0;
    else
      r0[0] <= _000_[0];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r0[1] <= 0;
    else
      r0[1] <= _000_[1];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r0[2] <= 0;
    else
      r0[2] <= _000_[2];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r0[3] <= 0;
    else
      r0[3] <= _000_[3];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r1[0] <= 0;
    else
      r1[0] <= _001_[0];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r1[1] <= 0;
    else
      r1[1] <= _001_[1];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r1[2] <= 0;
    else
      r1[2] <= _001_[2];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r1[3] <= 0;
    else
      r1[3] <= _001_[3];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r2[0] <= 0;
    else
      r2[0] <= _002_[0];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r2[1] <= 0;
    else
      r2[1] <= _002_[1];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r2[2] <= 0;
    else
      r2[2] <= _002_[2];
  (* src = "rtl/register_file.v:18" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      r2[3] <= 0;
    else
      r2[3] <= _002_[3];
endmodule
