/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* src = "rtl/alu_4bit.v:3.1-52.10" *)
module alu_4bit(a, b, op, result, zero, negative, carry);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  (* src = "rtl/alu_4bit.v:4.24-4.25" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "rtl/alu_4bit.v:5.24-5.25" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "rtl/alu_4bit.v:10.24-10.29" *)
  output carry;
  wire carry;
  (* src = "rtl/alu_4bit.v:9.24-9.32" *)
  output negative;
  wire negative;
  (* src = "rtl/alu_4bit.v:6.24-6.26" *)
  input [2:0] op;
  wire [2:0] op;
  (* src = "rtl/alu_4bit.v:7.24-7.30" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "rtl/alu_4bit.v:8.24-8.28" *)
  output zero;
  wire zero;
  assign _065_ = ~b[0];
  assign _066_ = op[0] | ~(op[1]);
  assign _067_ = op[2] & ~(_066_);
  assign _068_ = op[1] | ~(op[0]);
  assign _069_ = op[2] & ~(_068_);
  assign _070_ = ~(_069_ | _067_);
  assign _071_ = op[1] | op[0];
  assign _072_ = op[2] & ~(_071_);
  assign _073_ = ~op[2];
  assign _074_ = ~(op[1] & op[0]);
  assign _075_ = _073_ & ~(_074_);
  assign _076_ = _075_ | _072_;
  assign _077_ = _070_ & ~(_076_);
  assign _078_ = _073_ & ~(_071_);
  assign _079_ = _073_ & ~(_066_);
  assign _080_ = _073_ & ~(_068_);
  assign _081_ = _080_ | _079_;
  assign _082_ = _081_ | _078_;
  assign _083_ = _077_ & ~(_082_);
  assign _084_ = a[0] | ~(_067_);
  assign _085_ = _069_ & ~(a[0]);
  assign _086_ = _084_ & ~(_085_);
  assign _087_ = ~(a[0] ^ b[0]);
  assign _088_ = _072_ & ~(_087_);
  assign _089_ = ~(a[0] | b[0]);
  assign _090_ = _075_ & ~(_089_);
  assign _091_ = _090_ | _088_;
  assign _092_ = _086_ & ~(_091_);
  assign _093_ = a[0] & b[0];
  assign _094_ = _093_ & _079_;
  assign _095_ = _093_ | _089_;
  assign _096_ = _080_ & ~(_095_);
  assign _097_ = _096_ | _094_;
  assign _098_ = _078_ & ~(_087_);
  assign _099_ = _098_ | _097_;
  assign _100_ = _092_ & ~(_099_);
  assign _101_ = _083_ ? _065_ : _100_;
  assign result[0] = ~_101_;
  assign _102_ = a[1] ^ a[0];
  assign _103_ = _067_ & ~(_102_);
  assign _104_ = ~(a[1] ^ a[0]);
  assign _105_ = _069_ & ~(_104_);
  assign _106_ = _105_ | _103_;
  assign _107_ = ~(a[1] ^ b[1]);
  assign _108_ = _072_ & ~(_107_);
  assign _109_ = ~(a[1] | b[1]);
  assign _110_ = _075_ & ~(_109_);
  assign _111_ = _110_ | _108_;
  assign _112_ = _111_ | _106_;
  assign _113_ = ~(a[1] & b[1]);
  assign _114_ = _079_ & ~(_113_);
  assign _115_ = b[0] & ~(a[0]);
  assign _116_ = _115_ ^ _107_;
  assign _117_ = _080_ & ~(_116_);
  assign _118_ = _117_ | _114_;
  assign _119_ = _107_ ^ _093_;
  assign _120_ = _078_ & ~(_119_);
  assign _121_ = _120_ | _118_;
  assign _122_ = _121_ | _112_;
  assign result[1] = _083_ ? b[1] : _122_;
  assign _123_ = a[1] | a[0];
  assign _124_ = _123_ ^ a[2];
  assign _125_ = _067_ & ~(_124_);
  assign _126_ = ~(a[1] & a[0]);
  assign _127_ = _126_ ^ a[2];
  assign _128_ = _069_ & ~(_127_);
  assign _129_ = _128_ | _125_;
  assign _130_ = a[2] ^ b[2];
  assign _131_ = _130_ & _072_;
  assign _132_ = ~(a[2] | b[2]);
  assign _133_ = _075_ & ~(_132_);
  assign _134_ = _133_ | _131_;
  assign _135_ = _134_ | _129_;
  assign _136_ = ~(a[2] & b[2]);
  assign _137_ = _079_ & ~(_136_);
  assign _138_ = _132_ | ~(_136_);
  assign _139_ = b[1] | ~(a[1]);
  assign _140_ = _107_ & ~(_115_);
  assign _141_ = _139_ & ~(_140_);
  assign _142_ = _141_ ^ _138_;
  assign _143_ = _080_ & ~(_142_);
  assign _000_ = _143_ | _137_;
  assign _001_ = _093_ & ~(_107_);
  assign _002_ = _113_ & ~(_001_);
  assign _003_ = _002_ ^ _130_;
  assign _004_ = _078_ & ~(_003_);
  assign _005_ = _004_ | _000_;
  assign _006_ = _005_ | _135_;
  assign result[2] = _083_ ? b[2] : _006_;
  assign _007_ = ~a[3];
  assign _008_ = ~(_123_ | a[2]);
  assign _009_ = _008_ ^ _007_;
  assign _010_ = _067_ & ~(_009_);
  assign _011_ = a[2] & ~(_126_);
  assign _012_ = _011_ ^ _007_;
  assign _013_ = _069_ & ~(_012_);
  assign _014_ = _013_ | _010_;
  assign _015_ = ~(a[3] ^ b[3]);
  assign _016_ = _072_ & ~(_015_);
  assign _017_ = ~(a[3] | b[3]);
  assign _018_ = _075_ & ~(_017_);
  assign _019_ = _018_ | _016_;
  assign _020_ = _019_ | _014_;
  assign _021_ = ~(a[3] & b[3]);
  assign _022_ = _079_ & ~(_021_);
  assign _023_ = _021_ & ~(_017_);
  assign _024_ = b[2] | ~(a[2]);
  assign _025_ = ~_024_;
  assign _026_ = _138_ & ~(_141_);
  assign _027_ = _026_ | _025_;
  assign _028_ = _027_ ^ _023_;
  assign _029_ = _080_ & ~(_028_);
  assign _030_ = _029_ | _022_;
  assign _031_ = _002_ | ~(_130_);
  assign _032_ = ~(_031_ & _136_);
  assign _033_ = _032_ ^ _015_;
  assign _034_ = _078_ & ~(_033_);
  assign _035_ = _034_ | _030_;
  assign _036_ = _035_ | _020_;
  assign negative = _083_ ? b[3] : _036_;
  assign _037_ = _101_ & ~(result[1]);
  assign _038_ = negative | result[2];
  assign zero = _037_ & ~(_038_);
  assign _039_ = ~(a[3] | a[2]);
  assign _040_ = a[3] | a[2];
  assign _041_ = _123_ & ~(_040_);
  assign _042_ = _039_ & ~(_041_);
  assign _043_ = _067_ & ~(_042_);
  assign _044_ = ~(a[3] & a[2]);
  assign _045_ = _044_ | _126_;
  assign _046_ = _069_ & ~(_045_);
  assign _047_ = _046_ | _043_;
  assign _048_ = b[3] | ~(a[3]);
  assign _049_ = _025_ & ~(_023_);
  assign _050_ = _048_ & ~(_049_);
  assign _051_ = _138_ & ~(_023_);
  assign _052_ = _051_ & ~(_141_);
  assign _053_ = _050_ & ~(_052_);
  assign _054_ = _080_ & ~(_053_);
  assign _055_ = ~(_015_ | _136_);
  assign _056_ = _021_ & ~(_055_);
  assign _057_ = _130_ & ~(_015_);
  assign _058_ = _057_ & ~(_002_);
  assign _059_ = _056_ & ~(_058_);
  assign _060_ = _078_ & ~(_059_);
  assign _061_ = _060_ | _054_;
  assign _062_ = _061_ | _047_;
  assign _063_ = _080_ | _078_;
  assign _064_ = _070_ & ~(_063_);
  assign carry = _062_ & ~(_064_);
  assign result[3] = negative;
endmodule

(* src = "rtl/control_unit.v:3.1-146.10" *)
module control_unit(opcode, flag_zero_in, flag_neg_in, imm_mode, reg_write, mem_read, mem_write, mem_to_reg, alu_src, alu_op, pc_src, reg_sel, flag_write);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  (* src = "rtl/control_unit.v:13.25-13.31" *)
  output [2:0] alu_op;
  wire [2:0] alu_op;
  (* src = "rtl/control_unit.v:12.25-12.32" *)
  output alu_src;
  wire alu_src;
  (* src = "rtl/control_unit.v:6.25-6.36" *)
  input flag_neg_in;
  wire flag_neg_in;
  (* src = "rtl/control_unit.v:16.25-16.35" *)
  output flag_write;
  wire flag_write;
  (* src = "rtl/control_unit.v:5.25-5.37" *)
  input flag_zero_in;
  wire flag_zero_in;
  (* src = "rtl/control_unit.v:7.25-7.33" *)
  input imm_mode;
  wire imm_mode;
  (* src = "rtl/control_unit.v:9.25-9.33" *)
  output mem_read;
  wire mem_read;
  (* src = "rtl/control_unit.v:11.25-11.35" *)
  output mem_to_reg;
  wire mem_to_reg;
  (* src = "rtl/control_unit.v:10.25-10.34" *)
  output mem_write;
  wire mem_write;
  (* src = "rtl/control_unit.v:4.25-4.31" *)
  input [3:0] opcode;
  wire [3:0] opcode;
  (* src = "rtl/control_unit.v:14.25-14.31" *)
  output pc_src;
  wire pc_src;
  (* src = "rtl/control_unit.v:15.25-15.32" *)
  output [1:0] reg_sel;
  wire [1:0] reg_sel;
  (* src = "rtl/control_unit.v:8.25-8.34" *)
  output reg_write;
  wire reg_write;
  assign _003_ = opcode[3] & ~(opcode[2]);
  assign _004_ = opcode[1] & opcode[0];
  assign _005_ = ~(_004_ & _003_);
  assign _006_ = ~(opcode[1] | opcode[0]);
  assign _007_ = ~(opcode[2] & opcode[3]);
  assign _008_ = _006_ & ~(_007_);
  assign _009_ = _005_ & ~(_008_);
  assign _010_ = opcode[2] & opcode[3];
  assign _011_ = opcode[1] | ~(opcode[0]);
  assign _012_ = _010_ & ~(_011_);
  assign _013_ = _004_ & ~(_007_);
  assign _014_ = _013_ | _012_;
  assign _015_ = _009_ & ~(_014_);
  assign _016_ = opcode[0] | ~(opcode[1]);
  assign _017_ = _010_ & ~(_016_);
  assign _018_ = opcode[3] | ~(opcode[2]);
  assign _019_ = _006_ & ~(_018_);
  assign _020_ = _019_ | _017_;
  assign _021_ = opcode[1] & ~(opcode[0]);
  assign _022_ = opcode[2] | opcode[3];
  assign _023_ = _021_ & ~(_022_);
  assign _024_ = opcode[0] & ~(opcode[1]);
  assign _025_ = _024_ & ~(_022_);
  assign _026_ = _025_ | _023_;
  assign _027_ = _026_ | _020_;
  assign _028_ = _015_ & ~(_027_);
  assign _029_ = _006_ & ~(_022_);
  assign _030_ = _028_ & ~(_029_);
  assign _031_ = _003_ & ~(_016_);
  assign _032_ = _030_ & ~(_031_);
  assign _033_ = _003_ & ~(_011_);
  assign _034_ = _006_ & _003_;
  assign _035_ = _034_ | _033_;
  assign _036_ = _032_ & ~(_035_);
  assign _037_ = _024_ & ~(_018_);
  assign _038_ = _004_ & ~(_018_);
  assign _039_ = _021_ & ~(_018_);
  assign _040_ = _039_ | _038_;
  assign _041_ = _040_ | _037_;
  assign _042_ = _036_ & ~(_041_);
  assign _043_ = _038_ | _037_;
  assign _044_ = _043_ | _033_;
  assign alu_op[0] = _044_ | _042_;
  assign _045_ = _040_ | _031_;
  assign alu_op[1] = _045_ | _042_;
  assign _046_ = _035_ | _031_;
  assign alu_op[2] = _046_ | _042_;
  assign _047_ = _033_ | _031_;
  assign _048_ = _038_ | _034_;
  assign _049_ = _048_ | _047_;
  assign _050_ = _039_ | _037_;
  assign _051_ = _050_ | _019_;
  assign _052_ = _051_ | _049_;
  assign _053_ = _023_ | _017_;
  assign _054_ = _029_ | _025_;
  assign _055_ = _054_ | _053_;
  assign _056_ = _055_ | ~(_015_);
  assign _057_ = ~(_056_ | _052_);
  assign flag_write = _057_ ? imm_mode : _052_;
  assign _058_ = ~imm_mode;
  assign reg_sel[0] = _057_ ? _058_ : _052_;
  assign _059_ = _004_ & ~(_022_);
  assign _060_ = _031_ | _017_;
  assign _061_ = _060_ | _035_;
  assign _062_ = _015_ & ~(_061_);
  assign _063_ = opcode[2] & ~(opcode[3]);
  assign _064_ = _063_ | _029_;
  assign _065_ = _062_ & ~(_064_);
  assign alu_src = _059_ ? imm_mode : _065_;
  assign _066_ = _059_ | _012_;
  assign _067_ = _009_ & ~(_066_);
  assign _068_ = _017_ | _013_;
  assign _069_ = _068_ | _047_;
  assign _070_ = _067_ & ~(_069_);
  assign _071_ = _050_ | _048_;
  assign _072_ = _023_ | _019_;
  assign _073_ = _072_ | _029_;
  assign _074_ = _073_ | _071_;
  assign mem_read = _070_ & ~(_074_);
  assign _075_ = _025_ | _019_;
  assign _076_ = _075_ | _029_;
  assign _077_ = _076_ | _071_;
  assign mem_write = _070_ & ~(_077_);
  assign _000_ = _053_ | _029_;
  assign reg_write = _015_ & ~(_000_);
  assign _001_ = _012_ & flag_neg_in;
  assign _002_ = _008_ ? flag_zero_in : _001_;
  assign pc_src = _002_ | ~(_005_);
  assign mem_to_reg = mem_read;
  assign reg_sel[1] = 1'h0;
endmodule

(* top =  1  *)
(* src = "rtl/cpu_top.v:3.1-231.10" *)
module cpu_top(clk, rst_n, out_port, halt_out, debug_r0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "rtl/cpu_top.v:118.17-118.22" *)
  wire [3:0] alu_b;
  (* src = "rtl/cpu_top.v:24.18-24.24" *)
  wire [2:0] alu_op;
  (* src = "rtl/cpu_top.v:35.17-35.27" *)
  wire [3:0] alu_result;
  (* src = "rtl/cpu_top.v:23.62-23.69" *)
  wire alu_src;
  (* src = "rtl/cpu_top.v:132.19-132.24" *)
  (* unused_bits = "0" *)
  wire carry;
  (* src = "rtl/cpu_top.v:4.25-4.28" *)
  input clk;
  wire clk;
  (* src = "rtl/cpu_top.v:8.25-8.33" *)
  output [3:0] debug_r0;
  wire [3:0] debug_r0;
  (* src = "rtl/cpu_top.v:26.18-26.28" *)
  wire flag_write;
  (* src = "rtl/cpu_top.v:14.17-14.21" *)
  wire halt;
  (* src = "rtl/cpu_top.v:7.25-7.33" *)
  output halt_out;
  wire halt_out;
  (* src = "rtl/cpu_top.v:19.17-19.25" *)
  wire imm_mode;
  (* src = "rtl/cpu_top.v:20.17-20.24" *)
  wire [3:0] imm_val;
  (* src = "rtl/cpu_top.v:50.17-50.28" *)
  wire [8:0] instruction;
  (* src = "rtl/cpu_top.v:23.29-23.37" *)
  wire mem_read;
  (* src = "rtl/cpu_top.v:43.17-43.30" *)
  wire [3:0] mem_read_data;
  (* src = "rtl/cpu_top.v:23.50-23.60" *)
  wire mem_to_reg;
  (* src = "rtl/cpu_top.v:23.39-23.48" *)
  wire mem_write;
  (* src = "rtl/cpu_top.v:131.19-131.27" *)
  wire negative;
  (* src = "rtl/cpu_top.v:40.25-40.35" *)
  reg negative_r;
  (* src = "rtl/cpu_top.v:17.17-17.23" *)
  wire [3:0] opcode;
  (* src = "rtl/cpu_top.v:18.17-18.24" *)
  wire [3:0] operand;
  (* src = "rtl/cpu_top.v:6.25-6.33" *)
  output [3:0] out_port;
  wire [3:0] out_port;
  (* src = "rtl/cpu_top.v:46.17-46.24" *)
  reg [3:0] out_reg;
  (* src = "rtl/cpu_top.v:12.17-12.19" *)
  wire [3:0] pc;
  (* src = "rtl/cpu_top.v:12.21-12.28" *)
  wire [3:0] pc_next;
  (* src = "rtl/cpu_top.v:23.71-23.77" *)
  wire pc_src;
  (* src = "rtl/cpu_top.v:13.17-13.25" *)
  wire pc_write;
  (* src = "rtl/cpu_top.v:32.17-32.24" *)
  wire [3:0] r0_wire;
  (* src = "rtl/cpu_top.v:29.17-29.27" *)
  wire [3:0] read_data1;
  (* src = "rtl/cpu_top.v:29.29-29.39" *)
  wire [3:0] read_data2;
  (* src = "rtl/cpu_top.v:99.17-99.30" *)
  wire [1:0] read_reg1_mux;
  (* src = "rtl/cpu_top.v:25.18-25.25" *)
  wire [1:0] reg_sel;
  (* src = "rtl/cpu_top.v:23.18-23.27" *)
  wire reg_write;
  (* src = "rtl/cpu_top.v:5.25-5.30" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/cpu_top.v:30.17-30.27" *)
  wire [3:0] write_data;
  (* src = "rtl/cpu_top.v:31.17-31.26" *)
  wire [1:0] write_reg;
  (* src = "rtl/cpu_top.v:130.19-130.23" *)
  wire zero;
  (* src = "rtl/cpu_top.v:40.17-40.23" *)
  reg zero_r;
  assign _01_ = instruction[4] | ~(instruction[5]);
  assign _02_ = ~(instruction[7] & instruction[6]);
  assign _00_ = _02_ | _01_;
  assign _03_ = ~(instruction[5] & instruction[4]);
  assign halt = ~(_03_ | _02_);
  assign pc_write = ~halt;
  assign _04_ = reg_sel[1] | ~(reg_sel[0]);
  assign write_reg[0] = instruction[2] & ~(_04_);
  assign write_reg[1] = instruction[3] & ~(_04_);
  assign _05_ = _00_ ? instruction[2] : instruction[0];
  assign _06_ = instruction[7] | instruction[6];
  assign _07_ = _06_ | _01_;
  assign read_reg1_mux[0] = _07_ & _05_;
  assign _08_ = _00_ ? instruction[3] : instruction[1];
  assign read_reg1_mux[1] = _08_ & _07_;
  assign alu_b[0] = alu_src ? instruction[0] : read_data2[0];
  assign alu_b[1] = alu_src ? instruction[1] : read_data2[1];
  assign alu_b[2] = alu_src ? instruction[2] : read_data2[2];
  assign alu_b[3] = alu_src ? instruction[3] : read_data2[3];
  assign write_data[0] = mem_to_reg ? mem_read_data[0] : alu_result[0];
  assign write_data[1] = mem_to_reg ? mem_read_data[1] : alu_result[1];
  assign write_data[2] = mem_to_reg ? mem_read_data[2] : alu_result[2];
  assign write_data[3] = mem_to_reg ? mem_read_data[3] : alu_result[3];
  assign _09_ = ~pc[0];
  assign pc_next[0] = pc_src ? instruction[0] : _09_;
  assign _10_ = pc[1] ^ pc[0];
  assign pc_next[1] = pc_src ? instruction[1] : _10_;
  assign _11_ = ~(pc[1] & pc[0]);
  assign _12_ = ~(_11_ ^ pc[2]);
  assign pc_next[2] = pc_src ? instruction[2] : _12_;
  assign _13_ = pc[2] & ~(_11_);
  assign _14_ = _13_ ^ pc[3];
  assign pc_next[3] = pc_src ? instruction[3] : _14_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cpu_top.v:139.5-147.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) negative_r <= 1'h0;
    else if (flag_write) negative_r <= negative;
  (* src = "rtl/cpu_top.v:172.5-177.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out_reg[0] <= 1'h0;
    else if (!_00_) out_reg[0] <= read_data1[0];
  (* src = "rtl/cpu_top.v:172.5-177.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out_reg[1] <= 1'h0;
    else if (!_00_) out_reg[1] <= read_data1[1];
  (* src = "rtl/cpu_top.v:172.5-177.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out_reg[2] <= 1'h0;
    else if (!_00_) out_reg[2] <= read_data1[2];
  (* src = "rtl/cpu_top.v:172.5-177.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out_reg[3] <= 1'h0;
    else if (!_00_) out_reg[3] <= read_data1[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cpu_top.v:139.5-147.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) zero_r <= 1'h0;
    else if (flag_write) zero_r <= zero;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:125.14-133.6" *)
  alu_4bit alu (
    .a(read_data1),
    .b(alu_b),
    .carry(carry),
    .negative(negative),
    .op(alu_op),
    .result(alu_result),
    .zero(zero)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:80.18-94.6" *)
  control_unit ctrl (
    .alu_op(alu_op),
    .alu_src(alu_src),
    .flag_neg_in(negative_r),
    .flag_write(flag_write),
    .flag_zero_in(zero_r),
    .imm_mode(instruction[8]),
    .mem_read(mem_read),
    .mem_to_reg(mem_to_reg),
    .mem_write(mem_write),
    .opcode(instruction[7:4]),
    .pc_src(pc_src),
    .reg_sel(reg_sel),
    .reg_write(reg_write)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:150.17-157.6" *)
  data_memory dmem (
    .addr(instruction[3:0]),
    .clk(clk),
    .mem_read(mem_read),
    .mem_write(mem_write),
    .read_data(mem_read_data),
    .write_data(read_data1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:62.24-65.6" *)
  instruction_memory imem (
    .addr(pc),
    .instruction(instruction)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:53.21-60.6" *)
  program_counter pc_inst (
    .clk(clk),
    .halt(halt),
    .pc(pc),
    .pc_next(pc_next),
    .pc_write(pc_write),
    .rst_n(rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cpu_top.v:105.19-116.6" *)
  register_file rf (
    .clk(clk),
    .r0_out(r0_wire),
    .read_data1(read_data1),
    .read_data2(read_data2),
    .read_reg1(read_reg1_mux),
    .read_reg2(instruction[1:0]),
    .reg_write(reg_write),
    .rst_n(rst_n),
    .write_data(write_data),
    .write_reg(write_reg)
  );
  assign debug_r0 = r0_wire;
  assign halt_out = halt;
  assign imm_mode = instruction[8];
  assign imm_val = instruction[3:0];
  assign opcode = instruction[7:4];
  assign operand = instruction[3:0];
  assign out_port = out_reg;
endmodule

(* src = "rtl/data_memory.v:3.1-28.10" *)
module data_memory(clk, mem_read, mem_write, addr, write_data, read_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  (* src = "rtl/data_memory.v:7.25-7.29" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "rtl/data_memory.v:4.25-4.28" *)
  input clk;
  wire clk;
  (* src = "rtl/data_memory.v:15.13-15.14" *)
  wire [31:0] i;
  (* src = "rtl/data_memory.v:5.25-5.33" *)
  input mem_read;
  wire mem_read;
  (* src = "rtl/data_memory.v:6.25-6.34" *)
  input mem_write;
  wire mem_write;
  reg [3:0] \ram[0]  = 4'h0;
  reg [3:0] \ram[10]  = 4'h0;
  reg [3:0] \ram[11]  = 4'h0;
  reg [3:0] \ram[12]  = 4'h0;
  reg [3:0] \ram[13]  = 4'h0;
  reg [3:0] \ram[14]  = 4'h0;
  reg [3:0] \ram[15]  = 4'h0;
  reg [3:0] \ram[1]  = 4'h0;
  reg [3:0] \ram[2]  = 4'h0;
  reg [3:0] \ram[3]  = 4'h0;
  reg [3:0] \ram[4]  = 4'h0;
  reg [3:0] \ram[5]  = 4'h0;
  reg [3:0] \ram[6]  = 4'h0;
  reg [3:0] \ram[7]  = 4'h0;
  reg [3:0] \ram[8]  = 4'h0;
  reg [3:0] \ram[9]  = 4'h0;
  (* src = "rtl/data_memory.v:9.25-9.34" *)
  output [3:0] read_data;
  wire [3:0] read_data;
  (* src = "rtl/data_memory.v:8.25-8.35" *)
  input [3:0] write_data;
  wire [3:0] write_data;
  assign _095_ = ~mem_read;
  assign _096_ = addr[0] ? \ram[1] [0] : \ram[0] [0];
  assign _097_ = addr[0] ? \ram[3] [0] : \ram[2] [0];
  assign _098_ = addr[1] ? _097_ : _096_;
  assign _099_ = addr[0] ? \ram[5] [0] : \ram[4] [0];
  assign _100_ = addr[0] ? \ram[7] [0] : \ram[6] [0];
  assign _016_ = addr[1] ? _100_ : _099_;
  assign _017_ = addr[2] ? _016_ : _098_;
  assign _018_ = addr[0] ? \ram[9] [0] : \ram[8] [0];
  assign _019_ = addr[0] ? \ram[11] [0] : \ram[10] [0];
  assign _020_ = addr[1] ? _019_ : _018_;
  assign _021_ = addr[0] ? \ram[13] [0] : \ram[12] [0];
  assign _022_ = addr[0] ? \ram[15] [0] : \ram[14] [0];
  assign _023_ = addr[1] ? _022_ : _021_;
  assign _024_ = addr[2] ? _023_ : _020_;
  assign _025_ = addr[3] ? _024_ : _017_;
  assign read_data[0] = _025_ & ~(_095_);
  assign _026_ = addr[0] ? \ram[1] [1] : \ram[0] [1];
  assign _027_ = addr[0] ? \ram[3] [1] : \ram[2] [1];
  assign _028_ = addr[1] ? _027_ : _026_;
  assign _029_ = addr[0] ? \ram[5] [1] : \ram[4] [1];
  assign _030_ = addr[0] ? \ram[7] [1] : \ram[6] [1];
  assign _031_ = addr[1] ? _030_ : _029_;
  assign _032_ = addr[2] ? _031_ : _028_;
  assign _033_ = addr[0] ? \ram[9] [1] : \ram[8] [1];
  assign _034_ = addr[0] ? \ram[11] [1] : \ram[10] [1];
  assign _035_ = addr[1] ? _034_ : _033_;
  assign _036_ = addr[0] ? \ram[13] [1] : \ram[12] [1];
  assign _037_ = addr[0] ? \ram[15] [1] : \ram[14] [1];
  assign _038_ = addr[1] ? _037_ : _036_;
  assign _039_ = addr[2] ? _038_ : _035_;
  assign _040_ = addr[3] ? _039_ : _032_;
  assign read_data[1] = _040_ & ~(_095_);
  assign _041_ = addr[0] ? \ram[1] [2] : \ram[0] [2];
  assign _042_ = addr[0] ? \ram[3] [2] : \ram[2] [2];
  assign _043_ = addr[1] ? _042_ : _041_;
  assign _044_ = addr[0] ? \ram[5] [2] : \ram[4] [2];
  assign _045_ = addr[0] ? \ram[7] [2] : \ram[6] [2];
  assign _046_ = addr[1] ? _045_ : _044_;
  assign _047_ = addr[2] ? _046_ : _043_;
  assign _048_ = addr[0] ? \ram[9] [2] : \ram[8] [2];
  assign _049_ = addr[0] ? \ram[11] [2] : \ram[10] [2];
  assign _050_ = addr[1] ? _049_ : _048_;
  assign _051_ = addr[0] ? \ram[13] [2] : \ram[12] [2];
  assign _052_ = addr[0] ? \ram[15] [2] : \ram[14] [2];
  assign _053_ = addr[1] ? _052_ : _051_;
  assign _054_ = addr[2] ? _053_ : _050_;
  assign _055_ = addr[3] ? _054_ : _047_;
  assign read_data[2] = _055_ & ~(_095_);
  assign _056_ = addr[0] ? \ram[1] [3] : \ram[0] [3];
  assign _057_ = addr[0] ? \ram[3] [3] : \ram[2] [3];
  assign _058_ = addr[1] ? _057_ : _056_;
  assign _059_ = addr[0] ? \ram[5] [3] : \ram[4] [3];
  assign _060_ = addr[0] ? \ram[7] [3] : \ram[6] [3];
  assign _061_ = addr[1] ? _060_ : _059_;
  assign _062_ = addr[2] ? _061_ : _058_;
  assign _063_ = addr[0] ? \ram[9] [3] : \ram[8] [3];
  assign _064_ = addr[0] ? \ram[11] [3] : \ram[10] [3];
  assign _065_ = addr[1] ? _064_ : _063_;
  assign _066_ = addr[0] ? \ram[13] [3] : \ram[12] [3];
  assign _067_ = addr[0] ? \ram[15] [3] : \ram[14] [3];
  assign _068_ = addr[1] ? _067_ : _066_;
  assign _069_ = addr[2] ? _068_ : _065_;
  assign _070_ = addr[3] ? _069_ : _062_;
  assign read_data[3] = _070_ & ~(_095_);
  assign _071_ = addr[0] | addr[1];
  assign _072_ = addr[3] | addr[2];
  assign _073_ = _072_ | _071_;
  assign _000_ = mem_write & ~(_073_);
  assign _074_ = addr[1] | ~(addr[0]);
  assign _075_ = _074_ | _072_;
  assign _007_ = mem_write & ~(_075_);
  assign _076_ = addr[0] | ~(addr[1]);
  assign _077_ = _076_ | _072_;
  assign _008_ = mem_write & ~(_077_);
  assign _078_ = ~(addr[0] & addr[1]);
  assign _079_ = _078_ | _072_;
  assign _009_ = mem_write & ~(_079_);
  assign _080_ = addr[3] | ~(addr[2]);
  assign _081_ = _080_ | _071_;
  assign _010_ = mem_write & ~(_081_);
  assign _082_ = _080_ | _074_;
  assign _011_ = mem_write & ~(_082_);
  assign _083_ = _080_ | _076_;
  assign _012_ = mem_write & ~(_083_);
  assign _084_ = _080_ | _078_;
  assign _013_ = mem_write & ~(_084_);
  assign _085_ = ~(addr[3] & addr[2]);
  assign _086_ = _085_ | _071_;
  assign _003_ = mem_write & ~(_086_);
  assign _087_ = _085_ | _078_;
  assign _006_ = mem_write & ~(_087_);
  assign _088_ = _085_ | _076_;
  assign _005_ = mem_write & ~(_088_);
  assign _089_ = addr[2] | ~(addr[3]);
  assign _090_ = _089_ | _071_;
  assign _014_ = mem_write & ~(_090_);
  assign _091_ = _085_ | _074_;
  assign _004_ = mem_write & ~(_091_);
  assign _092_ = _089_ | _074_;
  assign _015_ = mem_write & ~(_092_);
  assign _093_ = _089_ | _076_;
  assign _001_ = mem_write & ~(_093_);
  assign _094_ = _089_ | _078_;
  assign _002_ = mem_write & ~(_094_);
  always @(posedge clk)
    if (_007_) \ram[1] [0] <= write_data[0];
  always @(posedge clk)
    if (_007_) \ram[1] [1] <= write_data[1];
  always @(posedge clk)
    if (_007_) \ram[1] [2] <= write_data[2];
  always @(posedge clk)
    if (_007_) \ram[1] [3] <= write_data[3];
  always @(posedge clk)
    if (_001_) \ram[10] [0] <= write_data[0];
  always @(posedge clk)
    if (_001_) \ram[10] [1] <= write_data[1];
  always @(posedge clk)
    if (_001_) \ram[10] [2] <= write_data[2];
  always @(posedge clk)
    if (_001_) \ram[10] [3] <= write_data[3];
  always @(posedge clk)
    if (_000_) \ram[0] [0] <= write_data[0];
  always @(posedge clk)
    if (_000_) \ram[0] [1] <= write_data[1];
  always @(posedge clk)
    if (_000_) \ram[0] [2] <= write_data[2];
  always @(posedge clk)
    if (_000_) \ram[0] [3] <= write_data[3];
  always @(posedge clk)
    if (_014_) \ram[8] [0] <= write_data[0];
  always @(posedge clk)
    if (_014_) \ram[8] [1] <= write_data[1];
  always @(posedge clk)
    if (_014_) \ram[8] [2] <= write_data[2];
  always @(posedge clk)
    if (_014_) \ram[8] [3] <= write_data[3];
  always @(posedge clk)
    if (_013_) \ram[7] [0] <= write_data[0];
  always @(posedge clk)
    if (_013_) \ram[7] [1] <= write_data[1];
  always @(posedge clk)
    if (_013_) \ram[7] [2] <= write_data[2];
  always @(posedge clk)
    if (_013_) \ram[7] [3] <= write_data[3];
  always @(posedge clk)
    if (_012_) \ram[6] [0] <= write_data[0];
  always @(posedge clk)
    if (_012_) \ram[6] [1] <= write_data[1];
  always @(posedge clk)
    if (_012_) \ram[6] [2] <= write_data[2];
  always @(posedge clk)
    if (_012_) \ram[6] [3] <= write_data[3];
  always @(posedge clk)
    if (_011_) \ram[5] [0] <= write_data[0];
  always @(posedge clk)
    if (_011_) \ram[5] [1] <= write_data[1];
  always @(posedge clk)
    if (_011_) \ram[5] [2] <= write_data[2];
  always @(posedge clk)
    if (_011_) \ram[5] [3] <= write_data[3];
  always @(posedge clk)
    if (_005_) \ram[14] [0] <= write_data[0];
  always @(posedge clk)
    if (_005_) \ram[14] [1] <= write_data[1];
  always @(posedge clk)
    if (_005_) \ram[14] [2] <= write_data[2];
  always @(posedge clk)
    if (_005_) \ram[14] [3] <= write_data[3];
  always @(posedge clk)
    if (_004_) \ram[13] [0] <= write_data[0];
  always @(posedge clk)
    if (_004_) \ram[13] [1] <= write_data[1];
  always @(posedge clk)
    if (_004_) \ram[13] [2] <= write_data[2];
  always @(posedge clk)
    if (_004_) \ram[13] [3] <= write_data[3];
  always @(posedge clk)
    if (_003_) \ram[12] [0] <= write_data[0];
  always @(posedge clk)
    if (_003_) \ram[12] [1] <= write_data[1];
  always @(posedge clk)
    if (_003_) \ram[12] [2] <= write_data[2];
  always @(posedge clk)
    if (_003_) \ram[12] [3] <= write_data[3];
  always @(posedge clk)
    if (_002_) \ram[11] [0] <= write_data[0];
  always @(posedge clk)
    if (_002_) \ram[11] [1] <= write_data[1];
  always @(posedge clk)
    if (_002_) \ram[11] [2] <= write_data[2];
  always @(posedge clk)
    if (_002_) \ram[11] [3] <= write_data[3];
  always @(posedge clk)
    if (_006_) \ram[15] [0] <= write_data[0];
  always @(posedge clk)
    if (_006_) \ram[15] [1] <= write_data[1];
  always @(posedge clk)
    if (_006_) \ram[15] [2] <= write_data[2];
  always @(posedge clk)
    if (_006_) \ram[15] [3] <= write_data[3];
  always @(posedge clk)
    if (_009_) \ram[3] [0] <= write_data[0];
  always @(posedge clk)
    if (_009_) \ram[3] [1] <= write_data[1];
  always @(posedge clk)
    if (_009_) \ram[3] [2] <= write_data[2];
  always @(posedge clk)
    if (_009_) \ram[3] [3] <= write_data[3];
  always @(posedge clk)
    if (_010_) \ram[4] [0] <= write_data[0];
  always @(posedge clk)
    if (_010_) \ram[4] [1] <= write_data[1];
  always @(posedge clk)
    if (_010_) \ram[4] [2] <= write_data[2];
  always @(posedge clk)
    if (_010_) \ram[4] [3] <= write_data[3];
  always @(posedge clk)
    if (_015_) \ram[9] [0] <= write_data[0];
  always @(posedge clk)
    if (_015_) \ram[9] [1] <= write_data[1];
  always @(posedge clk)
    if (_015_) \ram[9] [2] <= write_data[2];
  always @(posedge clk)
    if (_015_) \ram[9] [3] <= write_data[3];
  always @(posedge clk)
    if (_008_) \ram[2] [0] <= write_data[0];
  always @(posedge clk)
    if (_008_) \ram[2] [1] <= write_data[1];
  always @(posedge clk)
    if (_008_) \ram[2] [2] <= write_data[2];
  always @(posedge clk)
    if (_008_) \ram[2] [3] <= write_data[3];
  assign i = 32'd16;
endmodule

(* src = "rtl/instruction_memory.v:3.1-17.10" *)
module instruction_memory(addr, instruction);
  (* src = "rtl/instruction_memory.v:4.25-4.29" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "rtl/instruction_memory.v:10.13-10.14" *)
  wire [31:0] i;
  (* src = "rtl/instruction_memory.v:5.25-5.36" *)
  output [8:0] instruction;
  wire [8:0] instruction;
  assign i = 32'd16;
  assign instruction = 9'h000;
endmodule

(* src = "rtl/program_counter.v:3.1-20.10" *)
module program_counter(clk, rst_n, pc_write, halt, pc_next, pc);
  (* src = "rtl/program_counter.v:16.18-16.35" *)
  wire _0_;
  (* src = "rtl/program_counter.v:4.25-4.28" *)
  input clk;
  wire clk;
  (* src = "rtl/program_counter.v:7.25-7.29" *)
  input halt;
  wire halt;
  (* src = "rtl/program_counter.v:9.25-9.27" *)
  output [3:0] pc;
  reg [3:0] pc;
  (* src = "rtl/program_counter.v:8.25-8.32" *)
  input [3:0] pc_next;
  wire [3:0] pc_next;
  (* src = "rtl/program_counter.v:6.25-6.33" *)
  input pc_write;
  wire pc_write;
  (* src = "rtl/program_counter.v:5.25-5.30" *)
  input rst_n;
  wire rst_n;
  assign _0_ = pc_write & ~(halt);
  (* src = "rtl/program_counter.v:13.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pc[0] <= 1'h0;
    else if (_0_) pc[0] <= pc_next[0];
  (* src = "rtl/program_counter.v:13.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pc[1] <= 1'h0;
    else if (_0_) pc[1] <= pc_next[1];
  (* src = "rtl/program_counter.v:13.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pc[2] <= 1'h0;
    else if (_0_) pc[2] <= pc_next[2];
  (* src = "rtl/program_counter.v:13.5-18.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pc[3] <= 1'h0;
    else if (_0_) pc[3] <= pc_next[3];
endmodule

(* src = "rtl/register_file.v:3.1-55.10" *)
module register_file(clk, rst_n, reg_write, read_reg1, read_reg2, write_reg, write_data, read_data1, read_data2, r0_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  (* src = "rtl/register_file.v:4.25-4.28" *)
  input clk;
  wire clk;
  (* src = "rtl/register_file.v:16.17-16.19" *)
  reg [3:0] r0;
  (* src = "rtl/register_file.v:13.25-13.31" *)
  output [3:0] r0_out;
  wire [3:0] r0_out;
  (* src = "rtl/register_file.v:16.21-16.23" *)
  reg [3:0] r1;
  (* src = "rtl/register_file.v:16.25-16.27" *)
  reg [3:0] r2;
  (* src = "rtl/register_file.v:16.29-16.31" *)
  reg [3:0] r3;
  (* src = "rtl/register_file.v:11.25-11.35" *)
  output [3:0] read_data1;
  wire [3:0] read_data1;
  (* src = "rtl/register_file.v:12.25-12.35" *)
  output [3:0] read_data2;
  wire [3:0] read_data2;
  (* src = "rtl/register_file.v:7.25-7.34" *)
  input [1:0] read_reg1;
  wire [1:0] read_reg1;
  (* src = "rtl/register_file.v:8.25-8.34" *)
  input [1:0] read_reg2;
  wire [1:0] read_reg2;
  (* src = "rtl/register_file.v:6.25-6.34" *)
  input reg_write;
  wire reg_write;
  (* src = "rtl/register_file.v:5.25-5.30" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/register_file.v:10.25-10.35" *)
  input [3:0] write_data;
  wire [3:0] write_data;
  (* src = "rtl/register_file.v:9.25-9.34" *)
  input [1:0] write_reg;
  wire [1:0] write_reg;
  assign _004_ = write_reg[1] | ~(write_reg[0]);
  assign _002_ = reg_write & ~(_004_);
  assign _005_ = write_reg[0] | ~(write_reg[1]);
  assign _001_ = reg_write & ~(_005_);
  assign _006_ = write_reg[1] | write_reg[0];
  assign _003_ = reg_write & ~(_006_);
  assign _007_ = ~(write_reg[1] & write_reg[0]);
  assign _000_ = reg_write & ~(_007_);
  assign _008_ = ~(read_reg1[0] | read_reg1[1]);
  assign _009_ = ~(read_reg1[0] & read_reg1[1]);
  assign _010_ = r3[0] & ~(_009_);
  assign _011_ = read_reg1[0] | ~(read_reg1[1]);
  assign _012_ = r2[0] & ~(_011_);
  assign _013_ = _012_ | _010_;
  assign _014_ = read_reg1[1] | ~(read_reg1[0]);
  assign _015_ = r1[0] & ~(_014_);
  assign _016_ = _015_ | _013_;
  assign read_data1[0] = _008_ ? r0[0] : _016_;
  assign _017_ = r3[1] & ~(_009_);
  assign _018_ = r2[1] & ~(_011_);
  assign _019_ = _018_ | _017_;
  assign _020_ = r1[1] & ~(_014_);
  assign _021_ = _020_ | _019_;
  assign read_data1[1] = _008_ ? r0[1] : _021_;
  assign _022_ = r3[2] & ~(_009_);
  assign _023_ = r2[2] & ~(_011_);
  assign _024_ = _023_ | _022_;
  assign _025_ = r1[2] & ~(_014_);
  assign _026_ = _025_ | _024_;
  assign read_data1[2] = _008_ ? r0[2] : _026_;
  assign _027_ = r3[3] & ~(_009_);
  assign _028_ = r2[3] & ~(_011_);
  assign _029_ = _028_ | _027_;
  assign _030_ = r1[3] & ~(_014_);
  assign _031_ = _030_ | _029_;
  assign read_data1[3] = _008_ ? r0[3] : _031_;
  assign _032_ = ~(read_reg2[0] | read_reg2[1]);
  assign _033_ = ~(read_reg2[0] & read_reg2[1]);
  assign _034_ = r3[0] & ~(_033_);
  assign _035_ = read_reg2[0] | ~(read_reg2[1]);
  assign _036_ = r2[0] & ~(_035_);
  assign _037_ = _036_ | _034_;
  assign _038_ = read_reg2[1] | ~(read_reg2[0]);
  assign _039_ = r1[0] & ~(_038_);
  assign _040_ = _039_ | _037_;
  assign read_data2[0] = _032_ ? r0[0] : _040_;
  assign _041_ = r3[1] & ~(_033_);
  assign _042_ = r2[1] & ~(_035_);
  assign _043_ = _042_ | _041_;
  assign _044_ = r1[1] & ~(_038_);
  assign _045_ = _044_ | _043_;
  assign read_data2[1] = _032_ ? r0[1] : _045_;
  assign _046_ = r3[2] & ~(_033_);
  assign _047_ = r2[2] & ~(_035_);
  assign _048_ = _047_ | _046_;
  assign _049_ = r1[2] & ~(_038_);
  assign _050_ = _049_ | _048_;
  assign read_data2[2] = _032_ ? r0[2] : _050_;
  assign _051_ = r3[3] & ~(_033_);
  assign _052_ = r2[3] & ~(_035_);
  assign _053_ = _052_ | _051_;
  assign _054_ = r1[3] & ~(_038_);
  assign _055_ = _054_ | _053_;
  assign read_data2[3] = _032_ ? r0[3] : _055_;
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r0[0] <= 1'h0;
    else if (_003_) r0[0] <= write_data[0];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r0[1] <= 1'h0;
    else if (_003_) r0[1] <= write_data[1];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r0[2] <= 1'h0;
    else if (_003_) r0[2] <= write_data[2];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r0[3] <= 1'h0;
    else if (_003_) r0[3] <= write_data[3];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r1[0] <= 1'h0;
    else if (_002_) r1[0] <= write_data[0];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r1[1] <= 1'h0;
    else if (_002_) r1[1] <= write_data[1];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r1[2] <= 1'h0;
    else if (_002_) r1[2] <= write_data[2];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r1[3] <= 1'h0;
    else if (_002_) r1[3] <= write_data[3];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r2[0] <= 1'h0;
    else if (_001_) r2[0] <= write_data[0];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r2[1] <= 1'h0;
    else if (_001_) r2[1] <= write_data[1];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r2[2] <= 1'h0;
    else if (_001_) r2[2] <= write_data[2];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r2[3] <= 1'h0;
    else if (_001_) r2[3] <= write_data[3];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r3[0] <= 1'h0;
    else if (_000_) r3[0] <= write_data[0];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r3[1] <= 1'h0;
    else if (_000_) r3[1] <= write_data[1];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r3[2] <= 1'h0;
    else if (_000_) r3[2] <= write_data[2];
  (* src = "rtl/register_file.v:19.5-33.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) r3[3] <= 1'h0;
    else if (_000_) r3[3] <= write_data[3];
  assign r0_out = r0;
endmodule
